# Generated by Django 3.1.1 on 2020-09-18 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 11, 38, 59, 993960), verbose_name='date published'),
        ),
    ]
